#!/bin/bash

# assign variables
ACTION=${1}
version=1.0.1

function create_file() {

touch "${1}-54321"
}

function delete_file() {

if [ -z ${1} ] 
	then rm "server-54321"
	else rm "${1}-54321"
fi
}

function display_help() {

cat << EOF
Usage: ${0} {-c|--create|-h|--help|-d|--delete} <filename>

OPTIONS:
	-c | --create   Create a new file
	-h | --help	Display the command help
	-d | --delete   Delete the file

Examples:
	Create a new file:
		$ ${0} -c foo.txt

	Display help:
		$ ${0} -h

EOF
}

case "$ACTION" in
	-h|--help)
		display_help
		;;
	-c|--create)
		create_file "${2:-server}"
		;;
	-d|--delete)
		delete_file "${2}"
		;;
	*)
	echo "Usage ${0} {-c|-h}"
	exit 1
esac
